# Generated by Django 3.1.3 on 2020-11-16 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_adm', models.AutoField(primary_key=True, serialize=False)),
                ('rut_adm', models.CharField(max_length=13)),
                ('nombre_adm', models.CharField(max_length=25)),
                ('apellido_adm', models.CharField(max_length=35)),
                ('mail_adm', models.EmailField(max_length=254)),
                ('direccion_adm', models.CharField(max_length=200)),
                ('telefono_adm', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('rut_cli', models.CharField(max_length=13)),
                ('nombre_cli', models.CharField(max_length=25)),
                ('apellido_cli', models.CharField(max_length=35)),
                ('mail_cli', models.EmailField(max_length=254)),
                ('direccion_cli', models.CharField(max_length=200)),
                ('telefono_cli', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Comprobante_pago',
            fields=[
                ('id_comrpobante_pago', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'comprobante_pago',
            },
        ),
        migrations.CreateModel(
            name='Genero_producto',
            fields=[
                ('id_genero_producto', models.AutoField(primary_key=True, serialize=False)),
                ('gen_nombre', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'genero_producto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
                ('id_adm_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMicroCorpX.administrador')),
                ('id_genero_producto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMicroCorpX.genero_producto')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Tipo_pago',
            fields=[
                ('id_tipo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tp_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_pago',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now=True)),
                ('total', models.IntegerField()),
                ('id_cli_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMicroCorpX.cliente')),
                ('id_comprobante_pago_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMicroCorpX.comprobante_pago')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Venta_producto',
            fields=[
                ('id_venta_producto', models.AutoField(primary_key=True, serialize=False)),
                ('precio_total', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('id_producto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMicroCorpX.producto')),
                ('id_venta_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMicroCorpX.venta')),
            ],
            options={
                'db_table': 'venta_producto',
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='id_venta_producto_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMicroCorpX.venta_producto'),
        ),
        migrations.AddField(
            model_name='comprobante_pago',
            name='id_tipo_pago_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMicroCorpX.tipo_pago'),
        ),
        migrations.AddField(
            model_name='comprobante_pago',
            name='id_venta_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMicroCorpX.venta'),
        ),
    ]
